import os
import re
import sys

projectDir = sys.argv[1]
resultFile = os.path.join(projectDir,"WKJRouter_Mappings.h")

def scan_annotations(srcRoot, key, pre):
    cmd = 'grep -h -r "^' + key + '" ' + srcRoot + ' --include \'*.[mh]\''
    annList = os.popen(cmd).readlines()
    for ann in annList:
        path = ann.replace('(',',').split(',')[1]
        name = 'k'+pre+'Path'
        for comment in path.replace('_','/').split('/'):
            name += comment.capitalize()
            
        define = 'static NSString * const ' + name + ' = @"' + path + '";\n'
        print(define)
        file.write(define)

def clean():
    if os.path.exists(resultFile):
        os.remove(resultFile)

clean()
file = open(resultFile,'a')
file.write('//\n//  WKJRouter_Mappings.h\n')
file.write('//  This file is auto create by scan.py, do not edit this file')

file.write('\n\n#pragma mark ------------------WKJRouterController------------------\n')
scan_annotations(projectDir,'WKJRouterController','Controller')

file.write('\n\n#pragma mark -------------WKJRouterStoryboardController-------------\n')
scan_annotations(projectDir,'WKJRouterStoryboardController','SBController')

file.write('\n\n#pragma mark ----------------WKJRouterHandlerSelector---------------\n')
scan_annotations(projectDir,'WKJRouterHandlerSelector','Handler')
file.close()
